#!/bin/bash

brew install --cask temurin@25
brew trust clojure/tools
brew tap amar1729/formulae
brew trust --formula romkatv/powerlevel10k/powerlevel10k
brew install stow tmux tmuxpack/tpack/tpack figlet git romkatv/powerlevel10k/powerlevel10k eza perl bat helix fzf clojure/tools/clojure borkdude/brew/babashka chordii ghostscript pinentry-mac pass gitui nvim wget coreutils gnu-sed browserpass
brew install --cask font-hack-nerd-font font-meslo-lg-nerd-font
brew install --cask visual-studio-code

PREFIX='/opt/homebrew/opt/browserpass' make hosts-chrome-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'

stow --adopt zsh
stow tmux
stow git
stow bat
stow helix
stow clj
stow tools
stow -t ~/Library/Application\ Support/Code/User vscode
stow vim
stow gnupg

defaults write org.gpgtools.pinentry-mac UseKeychain -bool NO
defaults write org.gpgtools.pinentry-mac DisableKeychain -bool YES

gpgconf --kill gpg-agent .       

./dotvscode/install_extensions.clj
cp dotfiles-precommit-hook .git/hooks/pre-commit
