#!/bin/bash

brew install --cask temurin@25
brew trust clojure/tools
brew install stow tmux tmuxpack/tpack/tpack figlet git romkatv/powerlevel10k/powerlevel10k eza perl bat helix fzf clojure/tools/clojure borkdude/brew/babashka chordii ghostscript 
brew install --cask font-hack-nerd-font font-meslo-lg-nerd-font
brew install --cask visual-studio-code

stow --adopt zsh
stow tmux
stow git
stow bat
stow helix
stow clj
stow tools
stow -t ~/Libary/Application\ Support/Code/User vscode
stow dotvscode
